// Seeds a clearly-labelled DEMO election for one tenant, with locations, agents
// and simulated submissions, so the dashboard can be shown populated.
//
//   MONGODB_URI=... node scripts/seed-demo.mjs --tenant lp [--pus 120] [--report 0.7] [--live]
//
// --live keeps adding a submission every few seconds (to watch the dashboard update).
// Remove the demo afterwards from Setup → Details → Delete in the portal.
import mongoose from "mongoose";
import bcrypt from "bcryptjs";

const args = Object.fromEntries(
  process.argv.slice(2).reduce((acc, a, i, all) => {
    if (a.startsWith("--")) acc.push([a.slice(2), all[i + 1] && !all[i + 1].startsWith("--") ? all[i + 1] : true]);
    return acc;
  }, []),
);
const tenantId = args.tenant;
if (!tenantId || !process.env.MONGODB_URI) {
  console.error("Usage: MONGODB_URI=... node scripts/seed-demo.mjs --tenant <lp|ndc> [--pus 120] [--report 0.7] [--live]");
  process.exit(1);
}
const PU_COUNT = Number(args.pus ?? 120);
const REPORT = Number(args.report ?? 0.7);

await mongoose.connect(process.env.MONGODB_URI, { dbName: process.env.MONGODB_DB || "election_monitoring" });
const db = mongoose.connection.db;
const { ObjectId } = mongoose.Types;
const now = new Date();

const PARTIES = [
  ["APC", "All Progressives Congress", "#2563EB", "/election/parties/apc.jpg", 0.3],
  ["PDP", "Peoples Democratic Party", "#DC2626", "/election/parties/pdp.jpg", 0.22],
  ["LP", "Labour Party", "#16A34A", "/election/parties/lp.jpg", 0.24],
  ["NDC", "Nigeria Democratic Congress", "#0891B2", "/election/parties/ndc.jpeg", 0.12],
  ["APGA", "All Progressives Grand Alliance", "#CA8A04", "/election/parties/apga.jpg", 0.07],
  ["ADC", "African Democratic Congress", "#EA580C", "/election/parties/adc.jpg", 0.04],
  ["YPP", "Young Progressives Party", "#65A30D", "/election/parties/ypp.jpeg", 0.01],
];
const LGAS = ["Idemili North", "Onitsha North", "Awka South"];
const rand = (a, b) => Math.floor(a + Math.random() * (b - a + 1));

const electionId = new ObjectId();
await db.collection("elections").insertOne({
  _id: electionId, tenantId, name: "DEMO: Anambra Governorship (sample data)", type: "governorship",
  date: now, description: "Generated by scripts/seed-demo.mjs. All figures are fake.", status: "live",
  states: ["Anambra"], createdAt: now, updatedAt: now,
});
const base = { tenantId, electionId };

const parties = PARTIES.map(([code, name, color, logo, weight], order) => ({
  _id: new ObjectId(), ...base, code, name, candidateName: "", color, logo, order, weight, createdAt: now, updatedAt: now,
}));
await db.collection("parties").insertMany(parties.map(({ weight, ...p }) => p));

const locations = [];
const pus = [];
const wardsPerLga = 4;
const perWard = Math.max(1, Math.round(PU_COUNT / (LGAS.length * wardsPerLga)));
for (const [li, lgaName] of LGAS.entries()) {
  const lga = { _id: new ObjectId(), ...base, level: "lga", name: lgaName, code: "", state: "Anambra", registeredVoters: 0, createdAt: now, updatedAt: now };
  locations.push(lga);
  for (let w = 1; w <= wardsPerLga; w++) {
    const ward = { _id: new ObjectId(), ...base, level: "ward", name: `Ward ${String(w).padStart(2, "0")}`, code: String(w).padStart(2, "0"), state: "Anambra", lgaId: lga._id, registeredVoters: 0, createdAt: now, updatedAt: now };
    locations.push(ward);
    for (let p = 1; p <= perWard; p++) {
      const code = `04/${String(li + 1).padStart(2, "0")}/${String(w).padStart(2, "0")}/${String(p).padStart(3, "0")}`;
      const pu = { _id: new ObjectId(), ...base, level: "pu", name: `Polling Unit ${p}, ${ward.name}`, code, state: "Anambra", lgaId: lga._id, wardId: ward._id, registeredVoters: rand(350, 1100), createdAt: now, updatedAt: now };
      locations.push(pu);
      pus.push(pu);
    }
  }
}
await db.collection("locations").insertMany(locations);

const NAMES = ["Chinedu", "Ngozi", "Emeka", "Amaka", "Ifeanyi", "Chioma", "Obinna", "Adaeze", "Tobenna", "Uche", "Kelechi", "Nneka"];
const SURNAMES = ["Okafor", "Eze", "Nwosu", "Obi", "Okeke", "Nnamdi", "Igwe", "Anozie", "Chukwu", "Okonkwo"];
const demoPassword = "demo-pass";
const hash = await bcrypt.hash(demoPassword, 10);
const agents = pus.map((pu, i) => ({
  _id: new ObjectId(), ...base, name: `${NAMES[i % NAMES.length]} ${SURNAMES[(i * 7) % SURNAMES.length]}`, phone: `0803${String(1000000 + i).slice(-7)}`,
  username: `${tenantId}-demo-${electionId.toString().slice(-4)}-${i + 1}`, passwordHash: hash,
  pollingUnitId: pu._id, wardId: pu.wardId, lgaId: pu.lgaId, active: true,
  lastLoginAt: Math.random() < 0.85 ? now : undefined, createdAt: now, updatedAt: now,
}));
await db.collection("agents").insertMany(agents);

function makeSubmission(pu, agent, at) {
  const accredited = Math.round(pu.registeredVoters * (0.25 + Math.random() * 0.25));
  const rejected = rand(0, Math.round(accredited * 0.03));
  let remaining = accredited - rejected;
  const scores = parties.map((p, i) => {
    const v = i === parties.length - 1 ? remaining : Math.min(remaining, Math.round((accredited - rejected) * p.weight * (0.6 + Math.random() * 0.8)));
    remaining -= v;
    return { partyId: p._id, votes: Math.max(0, v) };
  });
  const totalValidVotes = scores.reduce((s, x) => s + x.votes, 0);
  const bad = Math.random() < 0.08;
  const roll = Math.random();
  const comment = roll < 0.06 ? "BVAS stopped working for about an hour, voting resumed after." : roll < 0.1 ? "Some thugs tried to disrupt voting but security restored order." : "";
  const status = bad ? "flagged" : Math.random() < 0.4 ? "verified" : "submitted";
  return {
    ...base, pollingUnitId: pu._id, wardId: pu.wardId, lgaId: pu.lgaId, agentId: agent._id, scores,
    registeredVoters: pu.registeredVoters, accreditedVoters: bad ? totalValidVotes - 20 : accredited, rejectedVotes: rejected,
    totalValidVotes, totalVotesCast: totalValidVotes + rejected,
    images: [{ url: "https://placehold.co/900x1200/png?text=Sample+result+sheet", thumbnailUrl: "", size: 0 }],
    comment, status, flags: bad ? ["over_accredited"] : [],
    history: [{ at, by: { role: "agent", id: String(agent._id), name: agent.name }, action: "submitted", changes: [], reason: "" }],
    submittedAt: at, createdAt: at, updatedAt: at,
  };
}

const reportCount = Math.round(pus.length * REPORT);
const order = pus.map((_, i) => i).sort(() => Math.random() - 0.5);
const start = Date.now() - 4 * 3600 * 1000;
const subs = order.slice(0, reportCount).map((i, k) => makeSubmission(pus[i], agents[i], new Date(start + (k / reportCount) * 4 * 3600 * 1000)));
if (subs.length) await db.collection("submissions").insertMany(subs);

console.log(`Seeded "${tenantId}" demo election ${electionId}: ${pus.length} PUs, ${agents.length} agents, ${subs.length} submissions.`);
console.log(`Agent logins: ${agents[0].username} … ${agents.at(-1).username}  (password: ${demoPassword})`);

if (args.live) {
  const left = order.slice(reportCount);
  console.log(`Live mode: adding one submission every 5s (${left.length} left). Ctrl+C to stop.`);
  for (const i of left) {
    await new Promise((r) => setTimeout(r, 5000));
    const s = makeSubmission(pus[i], agents[i], new Date());
    await db.collection("submissions").insertOne(s);
    console.log(`+ ${pus[i].name}`);
  }
}
await mongoose.disconnect();
